name: home_workout_app
description: A sleek Home Workout & Diet Planner App built using Flutter and Dart.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Video players
  video_player: ^2.9.2
  chewie: ^1.8.1
  youtube_player_flutter: ^8.1.2

  # UI Enhancements
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.2

  # Storage
  shared_preferences: ^2.3.3
  path_provider: ^2.1.4

  # Calendar + Notifications
  table_calendar: ^3.1.2
  flutter_local_notifications: ^17.2.2

  # Essentials
  intl: ^0.19.0
  url_launcher: ^6.3.1

  # Splash Screen (better UX)
  flutter_native_splash: ^2.4.1

  # App icon
  flutter_launcher_icons: ^0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Generate custom icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

# Generate beautiful splash screen
flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/icons/

